name: XRAY
author: Chaos
version: '${project.version}'
main: com.duckydeveloper.Main
api-version: '1.20'
commands:
  Minecord:
    description: Commands which interact with the plugin itself.
    permission: XRAY.reload
  Blockdc:
    description: Blocks the console from discord.
    permission: XRAY.blockdc
  freeze:
    description: Freezes the chosen player.
    permission: XRAY.freeze
  tempmute:
    description: Mutes a player.
    permission: XRAY.mute
  unmute:
    description: Unmutes a player.
    permission: XRAY.unmute